<?php

/**
 * Copyright 2021, 2024 5 Mode
 *
 * This file is part of Avatar Free.
 * 
 * Avatar Free is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Avatar Free is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.  
 * 
 * You should have received a copy of the GNU General Public License
 * along with Avatar Free. If not, see <https://www.gnu.org/licenses/>.
 *
 * const.inc
 * 
 * Avatar Free constant file.
 *
 * @author Daniele Bonini <my25mb@aol.com>
 * @copyrights (c) 2021, 2024, 5 Mode     
 */

if (!defined("PHP_BR")) {
  define('PHP_BR', "<br>");
}
if (!defined("PHP_CN")) {
  define('PHP_CN', "zh-CN");
}
if (!defined("PHP_EN")) {
  define('PHP_EN', "en-US");
}
if (!defined("PHP_ES")) {
  define('PHP_ES', "es-ES");
}
if (!defined("PHP_FR")) {
  define('PHP_FR', "fr-FR");
}
if (!defined("PHP_HYPHEN")) {
  define('PHP_HYPHEN', "-");
}
if (!defined("PHP_IT")) {
  define('PHP_IT', "it-IT");
}
if (!defined("PHP_PIPE")) {
  define('PHP_PIPE', "|");
}
if (!defined("PHP_FILE_PIPE")) {
  define('PHP_FILE_PIPE', ">");
}
if (!defined("PHP_SLASH")) {
  define('PHP_SLASH', "/");
}
if (!defined("PHP_SPACE")) {
  define('PHP_SPACE', " ");
}
if (!defined("PHP_STR")) {
  define('PHP_STR', "");
}
if (!defined("PHP_TILDE")) {
  define('PHP_TILDE', "~");
}
if (!defined("PHP_UNDERSCORE")) {
  define('PHP_UNDERSCORE', "_");
}
if (!defined("PHP_UPLOAD_ERR_OK")) {
  define('PHP_UPLOAD_ERR_OK', 0);
}
if (!defined("PHP_UPLOAD_ERR_INI_SIZE")) {
  define('PHP_UPLOAD_ERR_INI_SIZE', 1);
}
if (!defined("PHP_UPLOAD_ERR_FORM_SIZE")) {
  define('PHP_UPLOAD_ERR_FORM_SIZE', 2);
}
if (!defined("PHP_UPLOAD_ERR_PARTIAL")) {
  define('PHP_UPLOAD_ERR_PARTIAL', 3);
}
if (!defined("PHP_UPLOAD_ERR_NO_FILE")) {
  define('PHP_UPLOAD_ERR_NO_FILE', 4);
}
if (!defined("PHP_UPLOAD_ERR_NO_TMP_DIR")) {
  define('PHP_UPLOAD_ERR_NO_TMP_DIR', 6);
}
if (!defined("PHP_UPLOAD_ERR_CANT_WRITE")) {
  define('PHP_UPLOAD_ERR_CANT_WRITE', 7);
}
if (!defined("PHP_UPLOAD_ERR_EXTENSION")) {
  define('PHP_UPLOAD_ERR_EXTENSION', 8);
}
